###############
# Site settings
###############

title: 'Jawad Firdous'
description: >
  A software engineer with more than two years of experience in professional environment. My honed skills include problem
  solving and Rails framework. Also, I really converse well with jQuery, HTML and CSS.

keywords: >
  Jawad Firdous, ruby on rails, devsinc, Lums

baseurl: ''
url: 'https://jawadfirdous.me' # the base hostname & protocol for your site

person:
  name: 'Jawad Firdous'
  family_name: 'Firdous'
  given_name: 'Jawad'
  city: 'Lahore'
  country: 'Pakistan'
  education: 'studied Computer Engineering at LUMS , Lahore *(2010 - 2012)*'
  cwork: 'leads developement at [eduleaf](https://www.myintellirent.com){:target="_blank"}'

developer:
  - 'builds web, mobile and desktop applications'
  - 'is pretty seriously seeing **Ruby & Ruby on Rails**'
  - 'likes to spice things up with **JavaScript, HTML & CSS**'
  - 'enjoys the occasional dinner-and-a-movie with **Java(SE) & JRuby**'
  - 'has had flings with **Java(Android), C & PHP**'

professional:
  - >
    [DevsInc](http://devsinc.com){:target='_blank'}
    *(Senior Software Enginner; Sep. 2015 - present)*

  - >
    built web apps using Ruby on Rails at
    [DevsInc](http://devsinc.com){:target='_blank'}
    *(Software Enginner; Oct. 2013 - Dec. 2014)*

  - 'used to do freelance Java SE development'

social:
  github_username: 'jawad-firdous'
  github_pages_repo_url: 'https://github.com/jawad-firdous/jawad-firdous.github.io'
  linkedin_url: 'https://pk.linkedin.com/in/jawad-firdous-0b1a7886'
  email: 'hi@jawadfirdous.me'
  email_text: 'hi at jawadfirdous.me'


# Build settings
markdown: kramdown
